/* ============================================================
   PORTFOLIO — Danyela Ramos
   main.js
   ============================================================ */

/* ──────────────────────────────────────────
   TRANSLATIONS
   ────────────────────────────────────────── */
const i18n = {
  en: {
    /* Nav */
    'nav.about':      'About',
    'nav.skills':     'Skills',
    'nav.experience': 'Experience',
    'nav.projects':   'Projects',
    'nav.education':  'Education',
    'nav.contact':    'Contact',

    /* Hero */
    'hero.greeting':  "Hi, I'm",
    'hero.role':      'Software Engineer',
    'hero.subtitle':  'Building modern web applications with React, Next.js & Python',
    'hero.cta_work':  'See my work',
    'hero.cta_contact': 'Contact me',

    /* About */
    'about.title':   'About Me',
    'about.p1':      "I'm a Software Engineer passionate about tech, business, and people. With a background in Customer Success leadership, I bring a unique perspective to building products — I understand both the technical craft and the human impact behind every feature.",
    'about.p2':      "Currently working at <strong>Adian</strong>, building a B2B research platform, and at <strong>Outlier</strong>, training AI models by reviewing and improving front-end code. My stack focuses on React, Next.js, TypeScript, Tailwind, and Python/Django.",
    'about.p3':      "When I'm not coding, you'll find me on my mountain bike, playing drums, or planning my next trip somewhere new.",
    'about.langs':   'PT • EN • DE (basic)',
    'about.hobbies': 'Drums · Mountain Bike · Travel',
    'about.stat_dev':    'Years in Dev',
    'about.stat_proj':   'Projects Built',
    'about.stat_lang':   'Languages',
    'about.stat_passion':'Passion',

    /* Skills */
    'skills.title':     'Tech Stack',
    'skills.sub':       'Technologies I work with',
    'skills.frontend':  'Frontend',
    'skills.backend':   'Backend',
    'skills.databases': 'Databases',
    'skills.tools':     'Tools & Practices',

    /* Experience */
    'exp.title':    'Experience',
    'exp.present':  'Present',
    'exp.jul': 'Jul', 'exp.apr': 'Apr', 'exp.aug': 'Aug', 'exp.oct': 'Oct',
    'exp.indie_co': 'Independent App Developer',

    'exp.adian1': 'Designed and developed core features of a B2B research/insights platform using React, Next.js, TypeScript, Tailwind, and Material UI.',
    'exp.adian2': 'Built and maintained backend services with Node.js/Express and Django, integrating PostgreSQL and MongoDB.',
    'exp.adian3': 'Applied design system principles — reusable UI components, tokens and interaction patterns — ensuring platform consistency.',
    'exp.adian4': 'Delivered end-to-end product improvements from UX prototypes to production-ready features, increasing usability and stability.',
    'exp.out1': 'Created, tested, and refactored front-end code (React, Next.js, Tailwind) generated by AI models to substantially improve output quality.',
    'exp.out2': 'Contributed to Reinforcement Learning from Human Feedback (RLHF) projects with state-of-the-art large language models.',
    'exp.out3': 'T3 Coding Expert — LATAM Coders.',
    'exp.ind1': 'Designed and coded dynamic, responsive web applications using React.js, Next.js, and Tailwind CSS.',
    'exp.ind2': 'Developed RESTful APIs with Node.js and Express, integrating MongoDB for efficient data storage.',
    'exp.ind3': 'Applied Scrum and Kanban practices; implemented responsive UI/UX with Figma and Tailwind across multiple devices.',

    /* Projects */
    'proj.title': 'Projects',
    'proj.sub':   "Some things I've built",
    'proj.cta':   'View all on GitHub',
    'proj.no_desc': 'No description available.',

    /* Education */
    'edu.title': 'Education & Certifications',
    'edu.edu':   'Education',
    'edu.cert':  'Certifications',
    'edu.uel':   'Psychology & Human Resources Development',
    'edu.pm3':   'Product Management',
    'edu.par':   'Behavioral Management of Organizations',

    /* Certifications */
    'cert.agile': 'Agile Methodology – Scrum & Kanban',
    'cert.cs':    'Customer Success Certification',
    'cert.uiux':  'Certificate in UI/UX Design',
    'cert.en':    'Duolingo English – Advanced',
    'cert.hr':    'HR.Rocks – Performance Management',

    /* Contact */
    'contact.title': 'Get In Touch',
    'contact.text':  "I'm always open to new opportunities, collaborations, or just a friendly chat about tech. Feel free to reach out!",
    'contact.email': 'Email',

    /* Footer */
    'footer.made':   'Made with',
    'footer.by':     'by Danyela Ramos',
    'footer.rights': 'All rights reserved.',
  },

  pt: {
    /* Nav */
    'nav.about':      'Sobre',
    'nav.skills':     'Skills',
    'nav.experience': 'Experiência',
    'nav.projects':   'Projetos',
    'nav.education':  'Educação',
    'nav.contact':    'Contato',

    /* Hero */
    'hero.greeting':  'Olá, eu sou',
    'hero.role':      'Engenheira de Software',
    'hero.subtitle':  'Construindo aplicações web modernas com React, Next.js & Python',
    'hero.cta_work':  'Ver meus projetos',
    'hero.cta_contact': 'Fale comigo',

    /* About */
    'about.title':   'Sobre Mim',
    'about.p1':      "Sou Engenheira de Software apaixonada por tecnologia, negócios e pessoas. Com experiência em liderança de Customer Success, trago uma perspectiva única para a construção de produtos — entendo tanto o lado técnico quanto o impacto humano por trás de cada funcionalidade.",
    'about.p2':      "Atualmente trabalho na <strong>Adian</strong>, construindo uma plataforma B2B de research, e na <strong>Outlier</strong>, treinando modelos de IA revisando e melhorando código front-end. Meu stack é focado em React, Next.js, TypeScript, Tailwind e Python/Django.",
    'about.p3':      "Quando não estou codando, você me encontra pedalando, tocando bateria ou planejando minha próxima viagem.",
    'about.langs':   'PT • EN • DE (básico)',
    'about.hobbies': 'Bateria · Mountain Bike · Viagens',
    'about.stat_dev':    'Anos em Dev',
    'about.stat_proj':   'Projetos',
    'about.stat_lang':   'Idiomas',
    'about.stat_passion':'Paixão',

    /* Skills */
    'skills.title':     'Tech Stack',
    'skills.sub':       'Tecnologias com as quais trabalho',
    'skills.frontend':  'Frontend',
    'skills.backend':   'Backend',
    'skills.databases': 'Bancos de Dados',
    'skills.tools':     'Ferramentas & Práticas',

    /* Experience */
    'exp.title':    'Experiência',
    'exp.present':  'Presente',
    'exp.jul': 'Jul', 'exp.apr': 'Abr', 'exp.aug': 'Ago', 'exp.oct': 'Out',
    'exp.indie_co': 'Desenvolvedora Independente',

    'exp.adian1': 'Projetei e desenvolvi funcionalidades principais de uma plataforma B2B de research usando React, Next.js, TypeScript, Tailwind e Material UI.',
    'exp.adian2': 'Construí e mantive serviços de backend com Node.js/Express e Django, integrando PostgreSQL e MongoDB.',
    'exp.adian3': 'Apliquei princípios de design system — componentes UI reutilizáveis, tokens e padrões de interação — garantindo consistência na plataforma.',
    'exp.adian4': 'Entreguei melhorias de produto de ponta a ponta, de protótipos UX a funcionalidades prontas para produção.',
    'exp.out1': 'Criei, testei e refatorei código front-end (React, Next.js, Tailwind) gerado por modelos de IA para melhorar substancialmente a qualidade.',
    'exp.out2': 'Contribuí com projetos de RLHF (Reinforcement Learning from Human Feedback) com modelos de linguagem de última geração.',
    'exp.out3': 'T3 Coding Expert — LATAM Coders.',
    'exp.ind1': 'Projetei e desenvolvi aplicações web dinâmicas e responsivas usando React.js, Next.js e Tailwind CSS.',
    'exp.ind2': 'Desenvolvi APIs RESTful com Node.js e Express, integrando MongoDB para armazenamento de dados.',
    'exp.ind3': 'Apliquei práticas de Scrum e Kanban; implementei UI/UX responsivo com Figma e Tailwind em múltiplos dispositivos.',

    /* Projects */
    'proj.title': 'Projetos',
    'proj.sub':   'Algumas coisas que construí',
    'proj.cta':   'Ver todos no GitHub',
    'proj.no_desc': 'Sem descrição disponível.',

    /* Education */
    'edu.title': 'Educação & Certificações',
    'edu.edu':   'Educação',
    'edu.cert':  'Certificações',
    'edu.uel':   'Psicologia & Desenvolvimento de Recursos Humanos',
    'edu.pm3':   'Gestão de Produto',
    'edu.par':   'Gerenciamento Comportamental de Organizações',

    /* Certifications */
    'cert.agile': 'Metodologia Ágil – Scrum & Kanban',
    'cert.cs':    'Certificação de Customer Success',
    'cert.uiux':  'Certificado em Design UI/UX',
    'cert.en':    'Fluência Duolingo em Inglês: Avançado',
    'cert.hr':    'HR.Rocks – Gestão de Desempenho',

    /* Contact */
    'contact.title': 'Entre em Contato',
    'contact.text':  'Estou sempre aberta a novas oportunidades, colaborações ou apenas uma conversa sobre tecnologia. Não hesite em entrar em contato!',
    'contact.email': 'E-mail',

    /* Footer */
    'footer.made':   'Feito com',
    'footer.by':     'por Danyela Ramos',
    'footer.rights': 'Todos os direitos reservados.',
  },
};

/* ──────────────────────────────────────────
   LANGUAGE MANAGEMENT
   ────────────────────────────────────────── */
function detectLang() {
  const saved = localStorage.getItem('dr-lang');
  if (saved && i18n[saved]) return saved;
  const br = (navigator.language || navigator.userLanguage || 'en').toLowerCase();
  return br.startsWith('pt') ? 'pt' : 'en';
}

let lang = detectLang();
let cachedRepos = null;

function t(key) {
  return (i18n[lang] && i18n[lang][key]) || key;
}

function applyLang(newLang) {
  lang = newLang;
  localStorage.setItem('dr-lang', lang);
  document.documentElement.lang = lang;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const val = t(key);
    if (val.includes('<strong>')) {
      el.innerHTML = val;
    } else {
      el.textContent = val;
    }
  });

  const langEn = document.getElementById('lang-en');
  const langPt = document.getElementById('lang-pt');
  if (langEn) langEn.classList.toggle('active', lang === 'en');
  if (langPt) langPt.classList.toggle('active', lang === 'pt');

  // Re-render projects with updated "no description" text
  if (cachedRepos) renderProjects(cachedRepos);
}

function init() {
  const langToggle = document.getElementById('lang-toggle');
  const langEn = document.getElementById('lang-en');
  const langPt = document.getElementById('lang-pt');
  if (!langToggle || !langEn || !langPt) return;

  langToggle.addEventListener('click', () => {
    applyLang(lang === 'en' ? 'pt' : 'en');
  });
}

// Boot when DOM is ready (script may be in <head> after Vite build)
function boot() {
  init();
  applyLang(lang);
  loadProjects();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', boot);
} else {
  boot();
}

/* ──────────────────────────────────────────
   NAVBAR — scroll & mobile
   ────────────────────────────────────────── */
const navbar    = document.getElementById('navbar');
const hamburger = document.getElementById('hamburger');
const navLinks  = document.getElementById('nav-links');
const scrollBtn = document.getElementById('scroll-top');

if (navbar) {
  window.addEventListener('scroll', () => {
    navbar.classList.toggle('scrolled', window.scrollY > 50);
    if (scrollBtn) scrollBtn.classList.toggle('visible', window.scrollY > 500);
  }, { passive: true });
}

if (hamburger && navLinks) {
  hamburger.addEventListener('click', () => {
    hamburger.classList.toggle('open');
    navLinks.classList.toggle('open');
  });

  navLinks.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', () => {
      hamburger.classList.remove('open');
      navLinks.classList.remove('open');
    });
  });
}

/* ──────────────────────────────────────────
   ACTIVE NAV LINK on scroll
   ────────────────────────────────────────── */
const sections = Array.from(document.querySelectorAll('section[id]'));

function updateActiveNav() {
  if (!navLinks) return;
  const scrollY = window.scrollY + 110;
  sections.forEach(sec => {
    const top  = sec.offsetTop;
    const bot  = top + sec.offsetHeight;
    const link = navLinks.querySelector(`a[href="#${sec.id}"]`);
    if (link) link.classList.toggle('active', scrollY >= top && scrollY < bot);
  });
}
window.addEventListener('scroll', updateActiveNav, { passive: true });

/* ──────────────────────────────────────────
   SMOOTH SCROLL
   ────────────────────────────────────────── */
document.querySelectorAll('a[href^="#"]').forEach(a => {
  a.addEventListener('click', e => {
    const target = document.querySelector(a.getAttribute('href'));
    if (target) {
      e.preventDefault();
      const top = target.getBoundingClientRect().top + window.scrollY - 78;
      window.scrollTo({ top, behavior: 'smooth' });
    }
  });
});

if (scrollBtn) scrollBtn.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));

/* ──────────────────────────────────────────
   SCROLL ANIMATIONS (Intersection Observer)
   ────────────────────────────────────────── */
const animObserver = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (!entry.isIntersecting) return;

    const el = entry.target;
    // Stagger siblings within same parent
    const siblings = Array.from(el.parentElement.querySelectorAll('[data-animate]'))
      .filter(s => !s.classList.contains('visible'));
    const idx = siblings.indexOf(el);
    const delay = Math.max(0, idx) * 90;

    setTimeout(() => el.classList.add('visible'), delay);
    animObserver.unobserve(el);
  });
}, { threshold: 0.1, rootMargin: '0px 0px -40px 0px' });

document.querySelectorAll('[data-animate]').forEach(el => animObserver.observe(el));

/* ──────────────────────────────────────────
   CUSTOM CURSOR (desktop)
   ────────────────────────────────────────── */
if (window.matchMedia('(pointer: fine)').matches) {
  const cur = document.getElementById('cursor');
  const fol = document.getElementById('cursor-follower');
  if (cur && fol) {
    let mx = 0, my = 0, fx = 0, fy = 0;

    document.addEventListener('mousemove', e => {
      mx = e.clientX; my = e.clientY;
      cur.style.left = mx + 'px';
      cur.style.top  = my + 'px';
    });

    (function animFol() {
      fx += (mx - fx) * 0.13;
      fy += (my - fy) * 0.13;
      fol.style.left = fx + 'px';
      fol.style.top  = fy + 'px';
      requestAnimationFrame(animFol);
    })();

    document.querySelectorAll('a, button, .proj-card, .skill-cat, .stat-card').forEach(el => {
      el.addEventListener('mouseenter', () => {
        cur.style.width = '18px'; cur.style.height = '18px';
        fol.style.opacity = '0.75';
      });
      el.addEventListener('mouseleave', () => {
        cur.style.width = '10px'; cur.style.height = '10px';
        fol.style.opacity = '0.45';
      });
    });
  }
}

/* ──────────────────────────────────────────
   GITHUB PROJECTS
   ────────────────────────────────────────── */
const LANG_COLORS = {
  JavaScript:       '#f1e05a',
  TypeScript:       '#3178c6',
  Python:           '#3572A5',
  HTML:             '#e34c26',
  CSS:              '#563d7c',
  'Jupyter Notebook':'#DA5B0B',
  Shell:            '#89e051',
  Vue:              '#41b883',
  Svelte:           '#ff3e00',
};

function renderProjects(repos) {
  const grid = document.getElementById('projects-grid');
  if (!grid) return;
  if (!repos || !repos.length) {
    grid.innerHTML = `
      <div style="grid-column:1/-1;text-align:center;padding:2.5rem;color:var(--muted)">
        <p>Check out my work on
          <a href="https://github.com/ramosdanyela" target="_blank" rel="noopener"
             style="color:var(--accent)">GitHub</a>
        </p>
      </div>`;
    return;
  }

  grid.innerHTML = repos.map(r => {
    const color = LANG_COLORS[r.language] || 'var(--muted)';
    const desc  = r.description || t('proj.no_desc');
    return `
      <a class="proj-card" href="${r.html_url}" target="_blank" rel="noopener">
        <div class="proj-top">
          <div class="proj-icon"><i class="fas fa-folder-open"></i></div>
          <div class="proj-ext-links">
            <a href="${r.html_url}" target="_blank" rel="noopener" title="GitHub"
               onclick="event.stopPropagation()">
              <i class="fab fa-github"></i>
            </a>
            ${r.homepage ? `
            <a href="${r.homepage}" target="_blank" rel="noopener" title="Live demo"
               onclick="event.stopPropagation()">
              <i class="fas fa-external-link-alt"></i>
            </a>` : ''}
          </div>
        </div>
        <p class="proj-name">${r.name}</p>
        <p class="proj-desc">${desc}</p>
        <div class="proj-meta">
          ${r.language ? `
          <span class="proj-lang">
            <span class="lang-dot" style="background:${color}"></span>
            ${r.language}
          </span>` : ''}
          ${r.stargazers_count > 0 ? `
          <span class="proj-stars">
            <i class="far fa-star"></i> ${r.stargazers_count}
          </span>` : ''}
        </div>
      </a>`;
  }).join('');
}

async function loadProjects() {
  const grid = document.getElementById('projects-grid');
  if (!grid) return;

  const showFallback = () => {
    cachedRepos = null;
    grid.innerHTML = `
      <div style="grid-column:1/-1;text-align:center;padding:2.5rem;color:var(--muted)">
        <p>See my projects on
          <a href="https://github.com/ramosdanyela" target="_blank" rel="noopener"
             style="color:var(--accent)">GitHub ↗</a>
        </p>
      </div>`;
  };

  const timeout = (ms) => new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), ms));

  try {
    const res = await Promise.race([
      fetch('https://api.github.com/users/ramosdanyela/repos?sort=updated&per_page=30'),
      timeout(12000)
    ]);
    if (!res.ok) throw new Error(`GitHub API ${res.status}`);

    const all  = await res.json();
    const repos = all
      .filter(r => !r.fork)
      .sort((a, b) =>
        b.stargazers_count - a.stargazers_count ||
        new Date(b.updated_at) - new Date(a.updated_at)
      )
      .slice(0, 6);

    cachedRepos = repos;
    renderProjects(repos);
  } catch (err) {
    console.warn('GitHub API error:', err.message);
    showFallback();
  }
}
